const allServices = [
	{
		id: 1,
		title1: "personal care",
		title2: "we assist you with your day to day needs",
		quote: "Galaxy Home Care offers several care programs for seniors who are in need of assistance at home. We also have various non-medical services to ensure you can live each day at your best.",
		services: [
			" Bathroom & shower assistance",
			" Medication reminders & management",
			" Mobiltiy assistance",
			" Meal preperation",
			" and more",
		],
		className: "flex-row",
		img: "https://www.galaxyhomecarellc.com/wp-content/uploads/2021/12/facilities2.jpg",
	},
	{
		id: 2,
		title1: "home health aide",
		title2: "care and assistance suited to your needs",
		quote: "Living comfortably and independently at home doesn’t have to be hard, especially for the elderly. Even if you are managing old age, a chronic illness, or other health conditions, you can still receive the care and service you need to live a healthy and happy life. Our home health aides work closely with Registered Nurses to assist you with your needs so you can stay securely and conveniently in your own home.",
		services: [
			" Bathing",
			" Grooming and dressing",
			" Checking vital signs",
			" Meal planning and preparing",
			" Encouraging and helping with exercise",
			" Light housekeeping",
			" Turning and transferring",
		],
		className: "flex-row-reverse",
		img: "https://www.galaxyhomecarellc.com/wp-content/uploads/2021/12/facilities.jpg",
	},
	{
		id: 3,
		title1: "companion care",
		title2: "building a caring friendship",
		quote: "Having someone to depend and lean on can be beneficial to an older adult’s physical and mental health. Our companions at Galaxy Home Care provide you with friendship and assistance so that you don’t have to spend your day alone and with difficulty.",
		services: [
			"  Planning and keeping appointments",
			" Bedtime and morning assistance",
			" Grocery shopping",
			" Encouraging socialization",
			"  Playing care or doing hobbies",
			"  Organizing mail or bills",
		],
		className: "flex-row",
		img: "https://www.galaxyhomecarellc.com/wp-content/uploads/2021/12/facilities3.jpg",
	},
	{
		id: 4,
		title1: "homemaker services",
		title2: "we assist with household activities and other chores",
		quote: "Homemaking services ensure a client is assisted with general household duties such as housekeeping, laundry, and more. We care about the safety and cleanliness of your home, and our well-trained staff will help you to achieve it. Despite declining health issues, we believe that you deserve to continue living life with a smile on your face. Some services to guarantee a comfortable and easy lifestyle are as followed.",
		services: [
			"Housekeeping",
			" Safety and Welfare Checks",
			" Handyman Services (As Needed)",
			" Laundry and Ironing",
			" Window Washing",
			" Wall and oven cleaning",
			" Bed Making and Sheet Changing",
			" And more",
		],
		className: "flex-row-reverse",
		img: "https://www.galaxyhomecarellc.com/wp-content/uploads/2021/12/facilities5.jpg",
	},
	{
		id: 5,
		title1: "respite care",
		title2: "we take over you caregiving duties while you take a break",
		quote: "As a full-time caregiver, it is also important that you take care of your own well-being. Leaving yourself worn out and stressed over your various duties and responsibilities can lead to serious health problems. Galaxy Home Care provides you with the opportunity to take a break, so you can recharge and spend time with your family. Our respite care service gives you a peace of mind knowing that your patient is being looked after by experienced and attentive caregivers.",
		className: "flex-row",
		img: "https://www.galaxyhomecarellc.com/wp-content/uploads/2021/12/facilities4.jpg",
	},
];

